// Generates src/common/icon-data.js from the SVG files in icons/.
// The icons/ folder is the single source of truth: each icon's geometry lives
// in one .svg file, and this script transcribes the drawable children into a
// data map plus PascalCase name constants consumed by src/common/icons.js.
//
// Run with `npm run icons:generate`; it also runs automatically on every build.

const fs = require('fs');
const path = require('path');
const { Window } = require('happy-dom');

const ICONS_DIR = path.join(__dirname, '..', 'icons');
const OUT_FILE = path.join(__dirname, '..', 'src', 'common', 'icon-data.js');

// Elements we transcribe. The root <svg>'s own attributes are ignored -
// createSvg/setSvgContent set width/height/viewBox/fill themselves.
const DRAWABLE = new Set(['path', 'circle', 'rect', 'ellipse', 'line', 'polyline', 'polygon']);

function pascalCase(name) {
  return name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// Depth-first collect of drawable descriptors, flattening any <g> wrappers.
function collectParts(node, parts) {
  for (const child of Array.from(node.children)) {
    const tag = child.tagName.toLowerCase();
    if (tag === 'g') {
      collectParts(child, parts);
      continue;
    }
    if (!DRAWABLE.has(tag)) continue;
    const attrs = {};
    for (const attrName of child.getAttributeNames()) {
      attrs[attrName] = child.getAttribute(attrName);
    }
    parts.push({ tag, attrs });
  }
}

function main() {
  const window = new Window();
  const parser = new window.DOMParser();

  const files = fs
    .readdirSync(ICONS_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  const icons = [];
  for (const file of files) {
    const name = file.replace(/\.svg$/, '');
    const text = fs.readFileSync(path.join(ICONS_DIR, file), 'utf8');
    const doc = parser.parseFromString(text, 'image/svg+xml');
    const root = doc.documentElement;
    const parts = [];
    collectParts(root, parts);
    if (!parts.length) {
      throw new Error(`generate-icons: ${file} has no drawable elements`);
    }
    icons.push({ name, parts });
  }

  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/generate-icons.cjs from icons/*.svg. Do not edit by hand.');
  lines.push('');
  lines.push('export const iconPaths = {');
  for (const { name, parts } of icons) {
    lines.push(`  '${name}': [`);
    for (const { tag, attrs } of parts) {
      lines.push(`    { tag: '${tag}', attrs: ${JSON.stringify(attrs)} },`);
    }
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');
  for (const { name } of icons) {
    lines.push(`export const ${pascalCase(name)} = '${name}';`);
  }
  lines.push('');

  fs.writeFileSync(OUT_FILE, lines.join('\n'));
  console.warn(`generate-icons: wrote ${icons.length} icons to ${path.relative(path.join(__dirname, '..'), OUT_FILE)}`);
}

main();
